import SwiftUI

// MARK: - Concrete galaxy: 28 systems, relay lane network
enum GalaxyData {
    static let systems: [StarSystemDef] = [
        // id, name, trait, nativeOre, pos, surveyCost, claimTier
        StarSystemDef(id: 0,  name: "Helion Prime",    trait: .balanced,     nativeOre: .ferrite,  pos: CGPoint(x: 0.50, y: 0.52), surveyCost: 0,    claimTier: 0), // home
        StarSystemDef(id: 1,  name: "Vesta Reach",     trait: .resourceRich, nativeOre: .ferrite,  pos: CGPoint(x: 0.38, y: 0.40), surveyCost: 80,   claimTier: 0),
        StarSystemDef(id: 2,  name: "Cuprion",         trait: .resourceRich, nativeOre: .cuprite,  pos: CGPoint(x: 0.62, y: 0.40), surveyCost: 90,   claimTier: 0),
        StarSystemDef(id: 3,  name: "Silex Hollow",    trait: .resourceRich, nativeOre: .silicate, pos: CGPoint(x: 0.50, y: 0.66), surveyCost: 100,  claimTier: 0),
        StarSystemDef(id: 4,  name: "Tarsis Gate",     trait: .populated,    nativeOre: .ferrite,  pos: CGPoint(x: 0.30, y: 0.58), surveyCost: 140,  claimTier: 1),
        StarSystemDef(id: 5,  name: "Orrin Belt",      trait: .resourceRich, nativeOre: .cuprite,  pos: CGPoint(x: 0.70, y: 0.58), surveyCost: 150,  claimTier: 1),
        StarSystemDef(id: 6,  name: "Pyre Verge",      trait: .hazardous,    nativeOre: .isotope,  pos: CGPoint(x: 0.24, y: 0.28), surveyCost: 220,  claimTier: 1),
        StarSystemDef(id: 7,  name: "Halcyon Drift",   trait: .populated,    nativeOre: .silicate, pos: CGPoint(x: 0.76, y: 0.30), surveyCost: 200,  claimTier: 1),
        StarSystemDef(id: 8,  name: "Korrun Waste",    trait: .derelict,     nativeOre: .ferrite,  pos: CGPoint(x: 0.18, y: 0.46), surveyCost: 180,  claimTier: 1),
        StarSystemDef(id: 9,  name: "Marrow Deep",     trait: .hazardous,    nativeOre: .isotope,  pos: CGPoint(x: 0.40, y: 0.78), surveyCost: 260,  claimTier: 2),
        StarSystemDef(id: 10, name: "Cinder Span",     trait: .balanced,     nativeOre: .ferrite,  pos: CGPoint(x: 0.60, y: 0.78), surveyCost: 240,  claimTier: 2),
        StarSystemDef(id: 11, name: "Aurae Station",   trait: .populated,    nativeOre: .silicate, pos: CGPoint(x: 0.84, y: 0.50), surveyCost: 280,  claimTier: 2),
        StarSystemDef(id: 12, name: "Veil Nebula",     trait: .hazardous,    nativeOre: .isotope,  pos: CGPoint(x: 0.16, y: 0.66), surveyCost: 320,  claimTier: 2),
        StarSystemDef(id: 13, name: "Ostara Cluster",  trait: .resourceRich, nativeOre: .cuprite,  pos: CGPoint(x: 0.84, y: 0.70), surveyCost: 300,  claimTier: 2),
        StarSystemDef(id: 14, name: "Brann Hold",      trait: .derelict,     nativeOre: .silicate, pos: CGPoint(x: 0.28, y: 0.84), surveyCost: 340,  claimTier: 2),
        StarSystemDef(id: 15, name: "Solace Ring",     trait: .populated,    nativeOre: .ferrite,  pos: CGPoint(x: 0.70, y: 0.18), surveyCost: 360,  claimTier: 3),
        StarSystemDef(id: 16, name: "Thren Expanse",   trait: .resourceRich, nativeOre: .ferrite,  pos: CGPoint(x: 0.10, y: 0.34), surveyCost: 380,  claimTier: 3),
        StarSystemDef(id: 17, name: "Glaive Reach",    trait: .hazardous,    nativeOre: .isotope,  pos: CGPoint(x: 0.50, y: 0.90), surveyCost: 420,  claimTier: 3),
        StarSystemDef(id: 18, name: "Myrr Confluence", trait: .populated,    nativeOre: .cuprite,  pos: CGPoint(x: 0.90, y: 0.34), surveyCost: 400,  claimTier: 3),
        StarSystemDef(id: 19, name: "Dust Atoll",      trait: .resourceRich, nativeOre: .silicate, pos: CGPoint(x: 0.74, y: 0.86), surveyCost: 440,  claimTier: 3),
        StarSystemDef(id: 20, name: "Echo Vault",      trait: .derelict,     nativeOre: .cuprite,  pos: CGPoint(x: 0.08, y: 0.54), surveyCost: 460,  claimTier: 3),
        StarSystemDef(id: 21, name: "Naxa Forge",      trait: .resourceRich, nativeOre: .ferrite,  pos: CGPoint(x: 0.90, y: 0.62), surveyCost: 480,  claimTier: 4),
        StarSystemDef(id: 22, name: "Lumen Spire",     trait: .populated,    nativeOre: .silicate, pos: CGPoint(x: 0.86, y: 0.16), surveyCost: 520,  claimTier: 4),
        StarSystemDef(id: 23, name: "Rift Maw",        trait: .hazardous,    nativeOre: .isotope,  pos: CGPoint(x: 0.20, y: 0.16), surveyCost: 600,  claimTier: 4),
        StarSystemDef(id: 24, name: "Quill Drift",     trait: .balanced,     nativeOre: .cuprite,  pos: CGPoint(x: 0.40, y: 0.16), surveyCost: 560,  claimTier: 4),
        StarSystemDef(id: 25, name: "Sable Hollow",    trait: .derelict,     nativeOre: .ferrite,  pos: CGPoint(x: 0.12, y: 0.78), surveyCost: 640,  claimTier: 5),
        StarSystemDef(id: 26, name: "Zenith Array",    trait: .populated,    nativeOre: .silicate, pos: CGPoint(x: 0.92, y: 0.84), surveyCost: 700,  claimTier: 5),
        StarSystemDef(id: 27, name: "Oblivion Edge",   trait: .hazardous,    nativeOre: .isotope,  pos: CGPoint(x: 0.60, y: 0.92), surveyCost: 820,  claimTier: 5),
    ]

    static let lanes: [LaneDef] = [
        LaneDef(a: 0, b: 1, hops: 1, requiresTech: nil, hazard: 0.0),
        LaneDef(a: 0, b: 2, hops: 1, requiresTech: nil, hazard: 0.0),
        LaneDef(a: 0, b: 3, hops: 1, requiresTech: nil, hazard: 0.0),
        LaneDef(a: 1, b: 4, hops: 1, requiresTech: nil, hazard: 0.05),
        LaneDef(a: 2, b: 5, hops: 1, requiresTech: nil, hazard: 0.05),
        LaneDef(a: 1, b: 6, hops: 2, requiresTech: nil, hazard: 0.20),
        LaneDef(a: 2, b: 7, hops: 2, requiresTech: nil, hazard: 0.08),
        LaneDef(a: 4, b: 8, hops: 1, requiresTech: nil, hazard: 0.10),
        LaneDef(a: 3, b: 9, hops: 2, requiresTech: nil, hazard: 0.20),
        LaneDef(a: 3, b: 10, hops: 2, requiresTech: nil, hazard: 0.10),
        LaneDef(a: 5, b: 11, hops: 2, requiresTech: nil, hazard: 0.08),
        LaneDef(a: 6, b: 16, hops: 2, requiresTech: "t_longlane", hazard: 0.18),
        LaneDef(a: 8, b: 12, hops: 2, requiresTech: nil, hazard: 0.16),
        LaneDef(a: 5, b: 13, hops: 2, requiresTech: nil, hazard: 0.10),
        LaneDef(a: 9, b: 14, hops: 1, requiresTech: nil, hazard: 0.14),
        LaneDef(a: 7, b: 15, hops: 2, requiresTech: nil, hazard: 0.06),
        LaneDef(a: 11, b: 18, hops: 2, requiresTech: "t_longlane", hazard: 0.08),
        LaneDef(a: 10, b: 17, hops: 2, requiresTech: nil, hazard: 0.18),
        LaneDef(a: 7, b: 18, hops: 2, requiresTech: nil, hazard: 0.08),
        LaneDef(a: 13, b: 19, hops: 1, requiresTech: nil, hazard: 0.10),
        LaneDef(a: 8, b: 20, hops: 2, requiresTech: nil, hazard: 0.16),
        LaneDef(a: 11, b: 21, hops: 2, requiresTech: "t_longlane", hazard: 0.10),
        LaneDef(a: 15, b: 22, hops: 2, requiresTech: "t_longlane", hazard: 0.06),
        LaneDef(a: 6, b: 23, hops: 2, requiresTech: "t_jumpcore", hazard: 0.26),
        LaneDef(a: 1, b: 24, hops: 2, requiresTech: nil, hazard: 0.12),
        LaneDef(a: 14, b: 25, hops: 2, requiresTech: "t_jumpcore", hazard: 0.20),
        LaneDef(a: 19, b: 26, hops: 2, requiresTech: "t_jumpcore", hazard: 0.12),
        LaneDef(a: 17, b: 27, hops: 2, requiresTech: "t_jumpcore", hazard: 0.30),
        // a few cross links for richer graph
        LaneDef(a: 13, b: 21, hops: 1, requiresTech: nil, hazard: 0.10),
        LaneDef(a: 12, b: 20, hops: 1, requiresTech: nil, hazard: 0.14),
        LaneDef(a: 15, b: 18, hops: 1, requiresTech: nil, hazard: 0.06),
        LaneDef(a: 16, b: 23, hops: 1, requiresTech: "t_jumpcore", hazard: 0.22),
        LaneDef(a: 24, b: 15, hops: 2, requiresTech: "t_longlane", hazard: 0.08),
        LaneDef(a: 9, b: 17, hops: 1, requiresTech: nil, hazard: 0.16),
        LaneDef(a: 10, b: 13, hops: 1, requiresTech: nil, hazard: 0.08),
    ]
}
